[common]
platform = espressif32@6.7.0
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
lib_deps = someweisguy/esp_dmx@^4.1.0

[env:wakelight]
extends = common
src_dir = src
extra_scripts = pre:scripts/gen_index_html.py
build_flags =
  -DCONFIG_DMX_ISR_IN_IRAM=1

[env:diagnostic]
extends = common
src_dir = diagnostic
